global:
  tenant:
    name: "production"
    domain: "coachlibre.com"
  
  imageRegistry: "docker.io"
  imagePullSecrets: []

frontend:
  image:
    tag: "latest"
  
  replicaCount: 3
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

backend:
  image:
    tag: "latest"
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

postgres:
  auth:
    postgresPassword: "production-secure-password"
  primary:
    persistence:
      size: 50Gi
      storageClass: "fast-ssd"
