{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "coachlibre-stack.fullname" . }}-frontend
  labels:
    {{- include "coachlibre-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    {{- with .Values.frontend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.global.tenant.domain }}
    secretName: {{ include "coachlibre-stack.fullname" . }}-frontend-tls
  {{- end }}
  rules:
  - host: {{ .Values.global.tenant.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "coachlibre-stack.fullname" . }}-frontend
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
