apiVersion: v1
kind: Service
metadata:
  name: {{ include "coachlibre-stack.fullname" . }}-frontend
  labels:
    {{- include "coachlibre-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    {{- include "coachlibre-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
