replicaCount: 1

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 6333
  targetPort: 6333

ingress:
  enabled: false  # Internal access only

config:
  storage:
    optimizers:
      deleted_threshold: 0.2
      vacuum_min_vector_number: 1000
    hnsw_config:
      m: 16
      ef_construct: 128

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""
  accessMode: ReadWriteOnce

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
