replicaCount: 1

image:
  repository: livekit/livekit-server
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 7880
  targetPort: 7880

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

config:
  port: 7880
  bind_addresses: ["0.0.0.0"]
  api_key: "changeme"
  api_secret: "changeme"
  
  rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
