replicaCount: 2

image:
  repository: coachlibre/payload-backend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ""  # Will be templated
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  PAYLOAD_SECRET: ""
  DATABASE_URL: ""
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASS: ""

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: "payload"
  primary:
    persistence:
      enabled: true
      size: 10Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
