name: CI/CD Staging

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./applications/astro-frontend
        push: true
        tags: coachlibre/astro-frontend:staging-${{ github.sha }}
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./applications/payload-backend
        push: true
        tags: coachlibre/payload-backend:staging-${{ github.sha }}
    
    - name: Update Helm values
      run: |
        sed -i "s/tag: latest/tag: staging-${{ github.sha }}/g" helm-charts/coachlibre-stack/values-staging.yaml
    
    - name: Commit updated values
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add helm-charts/coachlibre-stack/values-staging.yaml
        git commit -m "Update staging images to ${{ github.sha }}" || exit 0
        git push
